#!/bin/sh
PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR $against | grep \\\\.php`
# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
        oIFS=$IFS
        IFS='
        '
        SFILES="$1"
        IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}
echo "Checking PHP Lint..."
for FILE in $SFILES
do
        php -l -d display_errors=0 $PROJECT/$FILE
        if [ $? != 0 ]
        then
                echo "Fix the error before commit."
                exit 1
        fi
        FILES="$FILES $PROJECT/$FILE"
done
if [ "$FILES" != "" ]
then
        echo "Running Code Sniffer..."
        ./vendor/bin/phpcs --standard=./vendor/sniperphp/code_check/ruleset.xml --encoding=utf-8 -n -p $FILES
        if [ $? != 0 ]
        then
                echo "Fix the error before commit."
                exit 1
        fi
fi
